---
- hosts: myhosts
  connection: local
  name: Set bios attribute and reboot
  gather_facts: False

  vars:
  - attribute_name: AdvancedRAS_MachineCheckRecovery
  - attribute_value: Disabled

  tasks:

  - shell: 'ansible --version'
    register: ansible_version

  - block:
    - name: Set {{ attribute_name }} to {{ attribute_value }} for ansible version less than 2.10.0
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: "{{ attribute_name }}"
        bios_attribute_value: "{{ attribute_value }}"
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 20
      register: bios_attribute_less
    when: ansible_version['full'] is version('2.10.0', '<')

  - block:
    - name: Set multiple bios attributes for ansible version greater than 2.10.0
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attributes:
          AdvancedRAS_MachineCheckRecovery: "Disabled"
          Processors_UPIPrefetcher:  "Disabled"
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 20
      register: bios_attribute_greater
    when: ansible_version['full'] is version('2.10.0', '>')

  - name: Reboot system to apply new BIOS settings
    redfish_command:
      category: Systems
      command: PowerForceRestart
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 20
    register: power
    when: bios_attribute_less.changed or bios_attribute_greater.changed
    ignore_errors: yes
